name: Publish to NPM

on:
  push:
    branches: [ main ]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  publish:
    runs-on: windows-latest
    if: github.event_name == 'push' || github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org/'
        cache: 'npm'
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build production engine
      run: npm run build:production
      
    - name: Run tests
      run: npm test
      
    - name: Version bump (if workflow_dispatch)
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
        
    - name: Auto version bump (if main branch push)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        npm version patch --no-git-tag-version
        
    - name: Update README with latest version
      run: |
        $version = (Get-Content package.json | ConvertFrom-Json).version
        $readme = Get-Content README.md -Raw
        $readme = $readme -replace 'npm install -g MAK3R-HUB@[\d\.]+', "npm install -g MAK3R-HUB@$version"
        Set-Content -Path README.md -Value $readme
      shell: powershell
      
    - name: Publish to NPM
      if: env.NPM_TOKEN != ''
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Dry run NPM publish (if no token)
      if: env.NPM_TOKEN == ''
      run: |
        echo "⚠️ NPM_TOKEN not set - running dry run"
        npm publish --dry-run --access public
      env:
        NODE_AUTH_TOKEN: ''
        
    - name: Create GitHub release
      if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      run: |
        $version = (Get-Content package.json | ConvertFrom-Json).version
        git add package.json README.md
        git commit -m "🚀 Release v$version" || echo "No changes to commit"
        git tag "v$version" || echo "Tag may already exist"
        git push origin main --tags || echo "Push completed"
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: npm-package
        path: MAK3R-HUB-*.tgz